const Discord = require('discord.js');
module.exports.run = async (client, msg, args) => {
let embed = new Discord.MessageEmbed()

        .setTitle('**Securité Commandes**')
        .addField("`*annonce`", "Faire une annonce")
        .addField("`*antiraidoff`", "Désactiver l'antiraid")
        .addField("`*antiraidon`", "Activer l'antiraid")
        .addField("`*avatar`", "Affichez l'image d'une personne")
        .addField("`*load-backup`", "Ajouter une sauvegarde sur un autre serveur")
        .addField("`*ban`", "bannir un utilisateur")
        .addField("`*casino`", "Un casino avec 0,05% de chance de gagnez")
        .addField("`*clear`", "Effacer un nombre de message")
        .addField("`*covid`", "Avoir les dernière info sur le covid")
        .addField("`*create`", "Faire une sauvegarde de votre serveur")
        .addField("`*email`", "Crée une email valide temporaire")
        .addField("`*giveaway`", "Crée un giveaway")
        .addField("`*help`", "**LOL.**")
        .addField("`*invit`", "Regardez les invitations sur un serveur d'un utilisateur")
        .addField("`*invite`", "Inviter le bot sur votre serveur")
        .addField("`*K4Tenda`", "Affichez des informations sur le bot")
        .addField("`*kick`", "Expulser un utilisateur d'un serveur")
        .addField("`*lock`", "Verouiller un channel")
        .addField("`*mute`, `Non fonctionnel`", "Mute un utilisateur")
        .addField("`*nuke`", "Effacer tout les messages d'un channel")
        .addField("`*pasbin`", "Entrez votre code en Javascript, python etc..")
        .addField("`*ping`", "Affichez le ping du bot")
        .addField("`*report`", "Report un utilisateur||Contacter le propriétaire du bot||")
        .addField("`*say`", "Envoyé un message via le bot")
        .addField("`*serveurinfo`", "Affichez des info sur un serveur")
        .addField("`*serveurlist`", "Voir la liste de serveur que le bot à rejoind")
        .addField("`**ui`", "Avoir des information sur vous-meme")
        .addField("`*unlock`", "Déverouiller un channel")
        .addField("`*uptime`", "Voir depuis combien de temps le bot est connectée")
        .addField("`*warn`", "Avertir un utilisateur")
        .addField("`Infos`", "Legenda X K4A'Tv !\nBot communautaire\nhttps://discord.gg/xGDAu8wf7d\nhttps://discord.gg/EuF7acjXf6")
        .setFooter('')
         .setAuthor(msg.author.username, msg.author.avatarURL)
         .setColor('#00ace6')
        msg.channel.send(embed)

let embed5 = new Discord.MessageEmbed()
.setTitle("Commandes musique")
.addField("`*join`", "Faire rejoindre le bot dans un channel vocal")
.addField("`*disconnect`", "Faire quitter le bot d'un channel vocal")
.addField("`Infos`", "Les commandes musique ne sont pas encore disponible\nRevenez bientot :D")
.setFooter('')
.setAuthor(msg.author.username, msg.author.avatarURL)
.setColor('#00ace6')
msg.channel.send(embed5)

}
module.exports.help = {
    name: 'help'
}